# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9323ff8870eae6bf6ae3ae07072487aa1d78d56143e61449f15636c8876ff176770e80151020c608258a05b8f69edf9ef8b2fd42eed875db6a7d4c4576d1cd16

test:
  secret_key_base: fb91177343d69a75625f53fe5680a248476fa2a42715e6700dd3ed0611cf58ea557ba97dca7489fadc31e47050171d0ba57c8a49bfe4ebe68f6c84e2ec2f1925

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
